var myString;
var myNum;
var myBool;
var myVar;
var strArray;
myString = 'Hello World'.slice(0, 3);
myNum = 5.5;
myBool = false;
myVar = "hello world";
strArray = ['hello', 'world'];
var strNumTuple;
strNumTuple = ['Hello', 3];
console.log(myNum);
console.log(myString);
console.log(myBool);
console.log(myVar);
